apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
  labels:
    app.kubernetes.io/name: cloudnative-platform
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "ProductionSecurePassword2026!"
